version: "3.8"

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - backend-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  backend-net:
    driver: overlay
    external: true
volumes:
  registry_data: